language: node_js

sudo: true

branchs:
  only:
    - master

services:
  - mongodb

node_js:
  - '12'

cache:
  directories:
    - node_modules

install:
  - yarn install

script:
  - yarn test
  - yarn build

after_success:
  - yarn test:codecov
