language: node_js

sudo: true

services:
  - mongodb

node_js:
  - '10'

cache:
  directories:
    - node_modules

jobs:
  include:
    - stage: test
      if: (branch = master) AND (NOT (type IN (pull_request)))
      script:
        - yarn install
        - yarn build
